Added rotary encoder interface and supporting units
libhal-google/libhal pull request #270
Opened 2022-06-28 03:44 UTC by MasterBoyd

2022-06-28 03:48 UTC, MasterBoyd commented
Resolves #172

2022-06-28 14:27 UTC, kammce requested changes
Make sure to add a unit test for this interface. It ensures that it can actually compile without throwing errors. 

Also reformat the commit to follow this format: https://cbea.ms/git-commit/

2022-06-28 14:27 UTC, kammce commented on include/libembeddedhal/rotary_encoder/unit.hpp
> +#include <cstdio>
```suggestion
#include <cstdint>
```
My guess is that this is what you meant in order to bring in std::int64_t.

2022-06-28 14:27 UTC, kammce commented on include/libembeddedhal/rotary_encoder/interface.hpp
> +#include "../percent.hpp"
```suggestion
```
Unnecessary includes.

2022-06-28 14:27 UTC, kammce commented on include/libembeddedhal/rotary_encoder/interface.hpp
> +#include <cstdint>
```suggestion
```
Unnecessary include.

2022-06-28 14:27 UTC, kammce commented on include/libembeddedhal/rotary_encoder/interface.hpp
> + * @brief Hardware abstraction interface for Rotary Encoder feedback devices.
```suggestion
 * @brief Hardware abstraction interface for devices that report rotational position of an actuator, knob, or some other system.
```

2022-06-28 14:27 UTC, kammce commented on include/libembeddedhal/rotary_encoder/interface.hpp
> +   *
We should clearly define the behavior and limits of this function here as well as caveats to its results. For example we should include the following (but not in list form as I have it):

1. Explain how this interface does not distinguish between absolute encoding and relative encoding.
2. Explain the maximum limits of `embed::angular_position`.

2022-06-28 14:27 UTC, kammce commented on include/libembeddedhal/rotary_encoder/interface.hpp
> +    return read();
```suggestion
    return driver_read();
```
Otherwise this is recursive

2022-06-29 13:37 UTC, kammce requested changes

2022-06-29 13:37 UTC, kammce commented on include/libembeddedhal/rotary_encoder/interface.hpp
> +   * (1 bit being 1.46 nanoradians).
```suggestion
   * The highest resolution that is supported is 1 nanoradian where 1 bit being 1.46 nanodegrees.
```

It would be best if this section was removed. Because there are rotational encoding sources that extend beyond 32-bits. An example is the RMD-X motors which only have a 16-bit resolution but they can track multiple rotations and produce a multi-turn encoder value with width of 48 bits.

2022-06-29 13:37 UTC, kammce commented on tests/rotary_encoder/interface.test.cpp
> +#include <boost/ut.hpp>
Add this file to the CMakeList.txt file in the root. Currently this is not in the unit tests suite.

2022-06-29 13:37 UTC, kammce commented on include/libembeddedhal/rotary_encoder/interface.hpp
> +   * semblance of the encoder's relative or absolute rotational reference.
```suggestion
   * The angular position can be relative, meaning that they initialize to an angular position 
   * of 0 and does not have information of its current orientation. 
   * The angular position can also be absolute, meaning that the encoder knows its current orientation 
   * at start and can return value a non-zero value at initialization.
   * This interface does not distinguish between these two encoder schemes.
```

2022-06-29 13:37 UTC, kammce commented on include/libembeddedhal/rotary_encoder/interface.hpp
> +   * semblance of the encoder's relative or absolute rotational reference.
I rewrote this to be a bit more explicit in the expected behavior of the API by stating what the return values would be with either scheme.

2022-06-29 19:31 UTC, kammce approved these changes, later dismissed

2022-06-29 19:58 UTC, kammce approved these changes

2022-06-29 19:58 UTC, merged