Frequency closest
libhal-google/libhal pull request #284
Opened 2022-07-11 18:02 UTC by herculanodavi

2022-07-11 22:27 UTC, kammce requested changes

2022-07-11 22:27 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +    auto is_applicable = [&](std::uint32_t p_candidate) -> bool {
```suggestion
    auto is_applicable = [this, p_selection_mode](std::uint32_t p_candidate) -> bool {
```

Let's try to refrain from capturing everything. Unreferenced captures should be optimized away by the compiler, but we can help it along by capturing what we need.

2022-07-11 22:27 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +    auto cost = [&](std::uint32_t p_candidate) -> std::uint32_t {
```suggestion
    auto cost = [&](std::uint32_t p_candidate) -> std::uint32_t {
```
Ditto here.

2022-07-11 22:27 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +    for (auto candidate = best; candidate != p_dividers.end(); candidate++) {
I feel like this pre-supposes that this is a sorted array. Or at least computes the first few entries that may not be applicable, then searches the rest. I feel like we can eliminate the `find_if` line and simply iterate from the start. 

This way we reduce code gen, just have 1 loop, but sacrifice some of the performance.

2022-07-11 22:27 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +    return *this / *best;
Sorry if this is some feature creep, but I think it would be beneficial, since we already calculated the best divider, to return both the resulting frequency as well as the that divider value in a struct. Personally not the biggest fan of std::pair as its hard to understand which element is which when they are the same type and their names are just first and second.

2022-07-12 07:52 UTC, herculanodavi commented on include/libembeddedhal/frequency.hpp
> +    return *this / *best;
Got it. 
I thought about making a
```
struct division {
  frequency result;
  uint32_t divider;
};
```
and define it inside the frequency class, but then I end up with the `incomplete type` problem.

2022-07-12 08:04 UTC, herculanodavi commented on include/libembeddedhal/frequency.hpp
> +    for (auto candidate = best; candidate != p_dividers.end(); candidate++) {
First please see below the forward declaration problem.

Since we are not always returning a value, I thought of iterators as an alternative to std::optional in the "best-carrying" variable. I thought of this solution for us to have a single loop:
```c++
    std::optional<division> best = std::nullopt;

    auto cost = [p_target](std::optional<division>& p_candidate) -> std::uint32_t {
      if(p_candidate.has_value()) {
        return distance(p_candidate->result.cycles_per_second(),
                        p_target.cycles_per_second());
      }
      return std::numeric_limits<std::uint32_t>::max();
    };

    auto is_applicable = [p_target, p_selection_mode](division& p_candidate) -> bool {
      switch (p_selection_mode) {
        case selection_mode::lower:
          return p_candidate.result <= p_target;
        case selection_mode::higher:
          return p_candidate.result >= p_target;
        case selection_mode::closest:
          return true;
        default:
          return false;
      }
    };

    for(std::uint32_t candidate_divider: p_dividers) {
      division candidate{*this / candidate_divider, candidate_divider};
      if(is_applicable(candidate) && cost(candidate) < cost(best)) {
          best = candidate;
      }
    }
    return best;
```
This doesn't compile, though, mainly because of what is said below

2022-07-12 18:36 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +    return *this / *best;
Thats really strange. You should be able to define a struct within the frequency class and use it. Thats quite strange.

2022-07-12 23:00 UTC, herculanodavi commented on include/libembeddedhal/frequency.hpp
> +    return *this / *best;
The problem is not using the struct, but rather the fact that one of the struct members is of type frequency, where it's not fully defined yet, I guess.

2022-07-13 00:05 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +    return *this / *best;
Oh gotcha! Yeah I can see this as an issue. Yeah thats unfortunate.

2022-07-13 02:21 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +    for (auto candidate = best; candidate != p_dividers.end(); candidate++) {
Gotcha. Makes me want to take many of these class functions and make them free functions. For now we can simply use std::pair.

2022-07-13 02:21 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +    for (auto candidate = best; candidate != p_dividers.end(); candidate++) {
I'll leave the choice of how to do this to you @herculanodavi .

2022-07-18 19:12 UTC, kammce requested changes

2022-07-18 19:12 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +   * @param p_dividers - the set of available dividers.
```suggestion
```
This parameter does not exist.

2022-07-18 19:12 UTC, kammce commented on include/libembeddedhal/frequency.hpp
> +   * @param p_last - iterator after the last item in the search space.
Maybe include some information in one of these fields that this is a set of available dividers.

2022-07-18 19:54 UTC, kammce submitted a review, later dismissed

2022-07-18 19:58 UTC, kammce commented
Looks like docs is failing due to:

```
/github/workspace/include/libembeddedhal/frequency.hpp:299: error: The following parameter of embed::frequency::closest(InputIt p_first, InputIt p_last, frequency p_target, selection_mode p_selection_mode) is not documented:
  parameter 'p_target'
```

2022-07-19 07:51 UTC, herculanodavi commented
@kammce I'm sorry for the long PR, but somehow I am not able to agree with the CI linter. 
I'm using `clang-format -i include/libembeddedhal/frequency.hpp` from the repository root folder multiple times in different conditions (idk, I tried moving the formatting around to see if it was a bug) and for some reason lint fails because of this line:
```
include/libembeddedhal/frequency.hpp:126:4: error: code should be clang-formatted [-Wclang-format-violations]
  {}
```
I really am unsure what to do 🤷‍♂️

2022-07-19 14:51 UTC, kammce approved these changes
I've seen this weird quark with CI. I thought I had fixed it by making the rules a bit more relaxed. I'll have to investigate this again. Merging this in now.

2022-07-19 14:53 UTC, merged