Add embed::rc_servo
libhal-google/libhal pull request #335
Opened 2022-07-26 21:58 UTC by MaliaLabor

Resolves #279

2022-07-26 22:39 UTC, kammce requested changes

2022-07-26 22:39 UTC, kammce commented on include/libembeddedhal/servo/rc.hpp
> +          { .x = percent::raw_min() / 2, .y = percent::raw_max() / 2 },
Why is this divided by 2?

2022-07-26 22:39 UTC, kammce commented on tests/servo/rc.test.cpp
> +    expect(expected4 == std::get<0>(pwm.spy_duty_cycle.call_history().at(4)));
Can you place `that %` in front of these so we can see the results if this fails? Add the `#include "ostreams.hpp"` to get the code needed for `that` to work.

2022-07-26 22:39 UTC, kammce commented on tests/servo/rc.test.cpp
> +
Can you make a test for when create fails for example when configure also fails.

2022-07-27 00:39 UTC, MaliaLabor commented on include/libembeddedhal/servo/rc.hpp
> +          { .x = percent::raw_min() / 2, .y = percent::raw_max() / 2 },
I was getting an overflow issue when I used the full range

2022-07-27 01:25 UTC, kammce commented
Please resolve the messages if they are fixed

2022-07-27 01:27 UTC, kammce commented on include/libembeddedhal/servo/rc.hpp
> +          { .x = percent::raw_min() / 2, .y = percent::raw_max() / 2 },
Yikes, well this is ok for now.

2022-07-27 01:27 UTC, kammce approved these changes

2022-07-27 05:51 UTC, merged