Add util functions for hertz
libhal-google/libhal pull request #387
Opened 2022-08-11 22:08 UTC by MaliaLabor

Issue #230

2022-08-11 22:16 UTC, kammce requested changes

2022-08-11 22:16 UTC, kammce commented on include/libhal/units.hpp
> +[[nodiscard]] constexpr std::int64_t cycles_per(
Overall do not use fixed point math here. We should be avoiding division by int64_t.

2022-08-11 22:16 UTC, kammce commented on include/libhal/units.hpp
> +[[nodiscard]] constexpr std::chrono::nanoseconds duration_from_cycles(
Overall do not use fixed point math here. We should be avoiding division by int64_t.

2022-08-11 22:16 UTC, kammce commented on include/libhal/units.hpp
> +constexpr std::chrono::duration<int64_t, Period> wavelength(hertz p_source)
Add another function that returns float rather than std::chrono::duration.

2022-08-11 22:16 UTC, kammce commented on include/libhal/units.hpp
> +  const std::int64_t duration = absolute_value(p_duration.count());
You don't need to use absolute value here.

2022-08-11 22:16 UTC, kammce commented on include/libhal/units.hpp
> +  const std::int64_t count =
Storing this in int64_t results in us doing integral math when we should be using floating point math.

2022-08-11 23:46 UTC, MaliaLabor commented
I'm not sure if I correctly resolved these issues so I left them unresolved for now

2022-08-12 15:04 UTC, kammce requested changes

2022-08-12 15:04 UTC, kammce commented on include/libhal/units.hpp
> +
Check bounds and if it exceeds int64_t return `std::errc::result_out_of_range` found here: https://en.cppreference.com/w/cpp/error/errc

2022-08-13 01:03 UTC, kammce requested changes

2022-08-13 01:03 UTC, kammce commented on include/libhal/units.hpp
> +  if (int_min > nanoseconds || nanoseconds > int_max) {
This is in the wrong for int_min.

Should be `int_min <= nanoseconds && nanoseconds <= int_max`

2022-08-13 03:21 UTC, MaliaLabor commented on include/libhal/units.hpp
> +  if (int_min > nanoseconds || nanoseconds > int_max) {
I had to use `if (!(int_min <= nanoseconds && nanoseconds <= int_max))` to get this work, is this correct?

2022-08-13 11:50 UTC, kammce approved these changes

2022-08-13 11:51 UTC, merged