Add comments to make rc_servo example driver
libhal-google/libhal pull request #402
Opened 2022-08-16 21:54 UTC by MaliaLabor

Resolves #236

2022-08-17 23:14 UTC, kammce requested changes

2022-08-17 23:14 UTC, kammce commented on include/libhal/servo/rc.hpp
> +// Use #pragma once is as an include guard for headers
```suggestion
// Use "#pragma once" as an include guard for headers
// This is required because ...
```

Explain in more detail why it is we choose to use pragma once.

2022-08-17 23:14 UTC, kammce commented on include/libhal/servo/rc.hpp
> +  // function returns a result<rc_servo> object.
Add a section about how the standard name for factory functions is `create` and how the function signature must be:

```C++
static result<type> create(/* ... args ... */) { /* ... */ }
```

2022-08-17 23:14 UTC, kammce commented on include/libhal/servo/rc.hpp
> +    // function.
```suggestion
    // Using HAL_CHECK will return any errors that occur from the factory
    // function allowing the caller to choose what to do with the error information.
```

Something more like that?

2022-08-17 23:14 UTC, kammce commented on include/libhal/servo/rc.hpp
>    hal::pwm* m_pwm;
```suggestion
  // Use a pointer here rather than a reference, because member references implicitly delete move constructors
  hal::pwm* m_pwm;
```

Please double check this before putting this comment in.

2022-08-18 02:36 UTC, MaliaLabor commented on include/libhal/servo/rc.hpp
>    hal::pwm* m_pwm;
I haven't been able to find any information to verify this. I'm not sure what to look up.

2022-08-24 17:35 UTC, kammce approved these changes

2022-08-24 17:35 UTC, kammce commented on include/libhal/servo/rc.hpp
>    hal::pwm* m_pwm;
A good google search query would be "reference members in C++ classes"

2022-08-24 17:35 UTC, kammce commented on include/libhal/servo/rc.hpp
>    hal::pwm* m_pwm;
Still need this filled out.

2022-08-24 17:35 UTC, merged