✅:sparkles: Angular velocity sensor interface
libhal-google/libhal pull request #712
Opened 2023-12-22 18:13 UTC by Coreyboy1820

Added the interface and the tests for inheriting, creation, and errors.

2023-12-23 16:56 UTC, kammce requested changes
Besides the formatting, this looks great. I will approve this PR once once the formatting is fixed.

2023-12-23 16:56 UTC, kammce commented on demos/CMakeLists.txt
> +#limitations under the License.
Fix whatever is happening with the license area.

2023-12-23 16:56 UTC, kammce commented on demos/CMakeLists.txt
> +              target_link_libraries(${ PROJECT_NAME } PRIVATE libhal::libhal)
Not sure where the indents and strange formatting is coming from, but can you fix this?

2023-12-23 23:00 UTC, Coreyboy1820 commented on demos/CMakeLists.txt
> +#limitations under the License.
Yeah, I think my clang-format was running on non-c++ files, ill fix my bash folder workaround to only format c++ files.

2023-12-28 22:04 UTC, kammce requested changes
The files still have formatting issues. See the python program for an example of what happens to the first line.

2023-12-28 22:04 UTC, kammce commented on .clang-format
> +ColumnLimit: 80
Add newline back

2023-12-28 23:21 UTC, Coreyboy1820 commented on .clang-format
> +ColumnLimit: 80
Odd, I changed this already but will do it again.

2023-12-28 23:37 UTC, Coreyboy1820 commented
> The files still have formatting issues. See the python program for an example of what happens to the first line.

Apologies, should all be fixed now.

2023-12-29 15:15 UTC, kammce approved these changes

2023-12-29 15:16 UTC, merged